#samconfig.toml
version = 0.1
[default.deploy.parameters]
stack_name = "domaingenerator"
resolve_s3 = true
s3_prefix = "domaingenerator"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "openai=\"openai\""
image_repositories = []